# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Waleed Ovase"
theme: kiko

# URL
baseurl:            "/"
#baseurl:            "waleedovase.com" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "//gfjaru.github.io/Kiko/about"
  - name:           "Download"
    href:           ""

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
