# Site settings
title: Waleed Ovase
email: 
description: > # this means to ignore newlines until "baseurl:"
  Sure, this works.  For now.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://waleedovase.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  waleedovase

# Build settings
markdown: kramdown
theme: Nice_Blog
